package api

type identification string
type region string
type queue string
type tier string
type division string
type champion int
type dataDragonURL string
type languageCode string

const (
	LanguageCodeCzechRepublic              languageCode   = "cs_CZ"
	LanguageCodeGreece                                    = "el_GR"
	LanguageCodePoland                                    = "pl_PL"
	LanguageCodeRomania                                   = "ro_RO"
	LanguageCodeHungary                                   = "hu_HU"
	LanguageCodeUnitedKingdom                             = "en_GB"
	LanguageCodeGermany                                   = "de_DE"
	LanguageCodeSpain                                     = "es_ES"
	LanguageCodeItaly                                     = "it_IT"
	LanguageCodeFrance                                    = "fr_FR"
	LanguageCodeJapan                                     = "ja_JP"
	LanguageCodeKorea                                     = "ko_KR"
	LanguageCodeMexico                                    = "es_MX"
	LanguageCodeArgentina                                 = "es_AR"
	LanguageCodeBrazil                                    = "pt_BR"
	LanguageCodeUnitedStates                              = "en_US"
	LanguageCodeAustralia                                 = "en_AU"
	LanguageCodeRussia                                    = "ru_RU"
	LanguageCodeTurkey                                    = "tr_TR"
	LanguageCodeMalaysia                                  = "ms_MY"
	LanguageCodeRepublicOfThePhilippines                  = "en_PH"
	LanguageCodeSingapore                                 = "en_SG"
	LanguageCodeThailand                                  = "th_TH"
	LanguageCodeVietNam                                   = "vn_VN"
	LanguageCodeIndonesia                                 = "id_ID"
	LanguageCodeMalaysiaChinese                           = "zh_MY"
	LanguageCodeChina                                     = "zh_CN"
	LanguageCodeTaiwan                                    = "zh_TW"
	QueueRankedSolo                        queue          = "RANKED_SOLO_5x5"
	QueueRankedFlex                                       = "RANKED_FLEX_SR"
	QueueRankedTwistedTreeline                            = "RANKED_FLEX_TT"
	TierIron                               tier           = "IRON"
	TierBronze                                            = "BRONZE"
	TierSilver                                            = "SILVER"
	TierGold                                              = "GOLD"
	TierPlatinum                                          = "PLATINUM"
	TierDiamond                                           = "DIAMOND"
	DivisionOne                            division       = "I"
	DivisionTwo                                           = "II"
	DivisionThree                                         = "III"
	DivisionFour                                          = "IV"
	identificationName                     identification = "name"
	identificationAccountID                               = "account"
	identificationPUUID                                   = "puuid"
	identificationSummonerID                              = "summonerID"
	RegionBrasil                           region         = "br1"
	RegionEuropeNorthEast                                 = "eun1"
	RegionEuropeWest                                      = "euw1"
	RegionJapan                                           = "jp1"
	RegionKorea                                           = "kr"
	RegionLatinAmericaNorth                               = "la1"
	RegionLatinAmericaSouth                               = "la2"
	RegionNorthAmerica                                    = "na1"
	RegionOceania                                         = "oc1"
	RegionTurkey                                          = "tr1"
	RegionRussia                                          = "ru"
	RegionPBE                                             = "pbe1"
	dataDragonBaseURL                      dataDragonURL  = "ddragon.leagueoflegends.com"
	dataDragonDataURLFormat                               = dataDragonBaseURL + "/cdn/%s/data/%s"
	dataDragonImageURLFormat                              = dataDragonBaseURL + "/cdn/%s/img"
	dataDragonImageURLFormatWithoutVersion                = dataDragonBaseURL + "/cdn/img"
	baseURL                                string         = "api.riotgames.com"
	apiTokenHeaderKey                                     = "X-Riot-Token"
)
